v2/outline: initial translation
the-road-to-learn-react/the-road-to-learn-react-korean pull request #55
Opened 2020-02-29 08:50 UTC by yyijoo

커밋 메시지 규칙이 따로 있는지 몰라 우선 생각난 대로 작성했습니다.
혹시 별도의 규칙이 있다면 말씀 주세요!

2020-02-29 22:49 UTC, sujinleeme requested changes
안녕하세요 개정판 첫  PR 을 보내주셔서 감사합니다. ❣️
커밋메시지는 따로 규칙이 없는데 지금처럼 영문으로 작성해주시면 됩니다.

2020-02-29 22:49 UTC, sujinleeme commented on manuscript/outline.md
> +- **데이터베이스 연결:** 규모가 커지는 리액트 애플리케이션은 결국 영속적인 데이터를 필요로 합니다. 데이터는 데이터베이스에 저장되어, 브라우저의 세션이 종료된 후에도 온전히 남아있어 사용자간 공유될 수 있어야 합니다. Firebase는 백엔드 애플리케이션 없이도 데이터베이스를 도입할 수 있는 가장 간단한 방법 중 하나입니다. 저의 책 "The Roa
["The Road to Firebase"](https://www.roadtofirebase.com/) 링크가 빠져있어요.

2020-02-29 22:49 UTC, sujinleeme commented on manuscript/outline.md
> +리액트 도움닫기를 모두 끝냈습니다. 당신이 이 책을 즐겁게 읽고 리액트에 대한 관심이 탄력 받았길 바랍니다. 이 책이 마음에 들었다면 리액트에를 더 공부하고 싶어하는 친구들에게 공유해주세요. Amazon이나 Goodreads에 리뷰를 남겨주시는 것도 더 좋은 콘텐츠를 만드는 데 도움이 됩니다.
아마존, 굿리드로 작성하는 것이 좋겠네요. 빠져있는 링크도 추가해주세요.
```
[아마존](https://amzn.to/2JHlP42) 
```

2020-02-29 22:49 UTC, sujinleeme commented on manuscript/outline.md
> +이제 다른 책이나 코스, 튜토리얼을 새로 시작하기 전에 애플리케이션을 발전시켜 당신만의 리액트 프로젝트로 만들어보길 추천합니다. 한 주 정도 개발해서 배포한 제품을 다른 사람들에게 보여주세요. 항상 저의 독자분들이 어떤 걸 만들었는지 보고 제가 또 어떻게 도와줄 수 있을지 배우고싶습니다.
* 당신 보다는 여러분 으로 고쳐주세요. 
* 띄워쓰기 오류가 있습니다.  배우고 싶습니다.

2020-02-29 22:49 UTC, sujinleeme commented on manuscript/outline.md
> +리액트 도움닫기를 모두 끝냈습니다. 당신이 이 책을 즐겁게 읽고 리액트에 대한 관심이 탄력 받았길 바랍니다. 이 책이 마음에 들었다면 리액트에를 더 공부하고 싶어하는 친구들에게 공유해주세요. Amazon이나 Goodreads에 리뷰를 남겨주시는 것도 더 좋은 콘텐츠를 만드는 데 도움이 됩니다.
당신을 여러분들로 고쳐주세요.
탄력 받았길 바랍니다 보다는 더 적절한 표현이 있을까요?

2020-02-29 22:49 UTC, sujinleeme commented on manuscript/outline.md
> +- **백엔드와 연결:** 지금까지 우리는 리액트로 프론트엔드 애플리케이션을 만들고, 데이터는 써드 파티 백엔드 API로 요청해 받았습니다. 다른 방법으로 데이터베이스에 연결된 백엔드 어플리케이션의 API를 도입해 인증과 권한 설정을 할 수도 있습니다. ["GraphQL 도움닫기"]https://www.roadtographql.com/)에서 어떻게 Gra
["GraphQL 도움닫기"]https://www.roadtographql.com/ ( 가 빠져있어요. 위에 The Road to firebase  명도 번역이 되어 있지 않아 일관성이 필요합니다.
 The Road to GraphQL 으로 두는 것이 좋겠네요. 

프론트엔드 애플리케이션에서 백엔드 애플리케이션으로 접근할 수 있는지 배울 수 있습니다.

접근이 아니라 주고 받는 전송 방식 하는데, 좀더 구체적으로 표현하면 좋겠습니다.

2020-02-29 22:49 UTC, sujinleeme commented on manuscript/outline.md
> +- **상태 관리:** 이번 학습에서는 리액트만을 이용해 로컬 컴퍼넌트 상태를 관리했습니다. 대부분의 애플리케이션에 활용할 수 있는 좋은 시작점이지만 리액트에 적용 가능한 외부 상태 관리 솔루션들도 있습니다. 저의 책 ["리덕스 도움닫기"](https://www.roadtoredux.com/)에서 가장 대중적으로 사용되는 솔루션을 다룹니다.
이번 학습에서는  -> 이 책에서는 

대부분의 애플리케이션에 활용할 수 있는 좋은 시작점이지만 리액트에 적용 가능한 외부 상태 관리 솔루션들도 있습니다. 저의 책 ["리덕스 도움닫기"](https://www.roadtoredux.com/)에서 가장 대중적으로 사용되는 솔루션을 다룹니다.

생략된 목적어가 많아 구체적으로 표현하는 것이 좋습니다.

이 책에서는 리액트만을 사용해 컴포넌트 상태를 관리했습니다. 처음 리액트를 배우는 단계에서는 내부 상태 관리 정도로만 충분하지만,  외부 상태 관리 방법에 대해서 아는 것이 중요합니다.  ["리덕스 도움닫기"](https://www.roadtoredux.com/)에서 가장 많이 사용되는 외부 상태 관리 도구인 리덕스를 다룹니다.

2020-02-29 22:49 UTC, sujinleeme commented on manuscript/outline.md
> +- **웹팩(Webpack)과 바벨(Babel) 사용** 이 책에서는 create-react-app을 사용해 애플리케이션을 설치했습니다. 어느 정도 리액트에 익숙해지면 create-react-app을 사용하지 않고 프로젝트를 다루고 싶을 것입니다. 처음에는 [웹팩](https://www.robinwieruch.de/minimal-react-webpack-
**웹팩(Webpack)과 바벨(Babel) 사용**  ':'이 빠져있네요.

2020-02-29 22:49 UTC, sujinleeme commented on manuscript/outline.md
>  * **Testing:** We only scratched the surface of testing. If you are unfamiliar with testing web applications, [dive deeper into unit testing and integration testing](https://www.robinwieruch.de/react
영어 부분을 삭제해주세요.

2020-02-29 22:49 UTC, sujinleeme commented on manuscript/outline.md
> +- **타입 검사:** 이 책에서 리액트의 TypeScript를 사용했습니다. 이는 버그를 방지하고 개발자의 작업을 개선합니다. TypeScript를 깊이 들여다보고 적용하시면 자바스크립트 애플리케이션을 더욱 탄탄하게 만들 수 있습니다. 어쩌면 자바스크립트 대신 계속 TypeScript를 쓰게될 수도 있습니다.
타입스크립트로 사용해주세요.

2020-02-29 22:49 UTC, sujinleeme commented on manuscript/outline.md
> +* **리액트 네이티브:** [리액트 네이티브](https://facebook.github.io/react-native/)로 기존의 애플리케이션을 iOS와 Android와 같은 모바일 기기용 애플리케이션으로 만들 수 있습니다. 리액트에 대해 이미 잘 알고 있다면 리액트 네이티브는 쉽게 시작할 수 있습니다. 리액트와 리액트 네이티브의 기본적인 내용은 같습니
Android를 안드로이드로 고쳐주세요.

2020-03-01 02:13 UTC, yein9 commented on manuscript/outline.md
> +리액트 도움닫기를 모두 끝냈습니다. 당신이 이 책을 즐겁게 읽고 리액트에 대한 관심이 탄력 받았길 바랍니다. 이 책이 마음에 들었다면 리액트에를 더 공부하고 싶어하는 친구들에게 공유해주세요. Amazon이나 Goodreads에 리뷰를 남겨주시는 것도 더 좋은 콘텐츠를 만드는 데 도움이 됩니다.
'커졌길 바랍니다.', '관심을 갖는 계기가 되었길 바랍니다' 어떨까요?

2020-03-05 07:42 UTC, yyijoo commented on manuscript/outline.md
> +- **데이터베이스 연결:** 규모가 커지는 리액트 애플리케이션은 결국 영속적인 데이터를 필요로 합니다. 데이터는 데이터베이스에 저장되어, 브라우저의 세션이 종료된 후에도 온전히 남아있어 사용자간 공유될 수 있어야 합니다. Firebase는 백엔드 애플리케이션 없이도 데이터베이스를 도입할 수 있는 가장 간단한 방법 중 하나입니다. 저의 책 "The Roa
반영했습니다

2020-03-05 07:43 UTC, yyijoo commented on manuscript/outline.md
> +리액트 도움닫기를 모두 끝냈습니다. 당신이 이 책을 즐겁게 읽고 리액트에 대한 관심이 탄력 받았길 바랍니다. 이 책이 마음에 들었다면 리액트에를 더 공부하고 싶어하는 친구들에게 공유해주세요. Amazon이나 Goodreads에 리뷰를 남겨주시는 것도 더 좋은 콘텐츠를 만드는 데 도움이 됩니다.
여러분으로 바꾸고 '커졌길 바랍니다.'를 적용했습니다!

2020-03-05 07:43 UTC, yyijoo commented on manuscript/outline.md
> +이제 다른 책이나 코스, 튜토리얼을 새로 시작하기 전에 애플리케이션을 발전시켜 당신만의 리액트 프로젝트로 만들어보길 추천합니다. 한 주 정도 개발해서 배포한 제품을 다른 사람들에게 보여주세요. 항상 저의 독자분들이 어떤 걸 만들었는지 보고 제가 또 어떻게 도와줄 수 있을지 배우고싶습니다.
반영했습니다

2020-03-05 07:54 UTC, yyijoo commented on manuscript/outline.md
> +- **백엔드와 연결:** 지금까지 우리는 리액트로 프론트엔드 애플리케이션을 만들고, 데이터는 써드 파티 백엔드 API로 요청해 받았습니다. 다른 방법으로 데이터베이스에 연결된 백엔드 어플리케이션의 API를 도입해 인증과 권한 설정을 할 수도 있습니다. ["GraphQL 도움닫기"]https://www.roadtographql.com/)에서 어떻게 Gra
1) 프론트엔드 애플리케이션에서 백엔드 애플리케이션으로부터 필요한 데이터를 직접 정의하는지 배울 수 있습니다. 
2) 프론트엔드 애플리케이션에서 백엔드 애플레이션과 더 능동적으로 통신할 수 있는지 배울 수 있습니다.

이정도는 어떤가요? 너무 의역한 것 같기도 하고.. 혹시 더 좋은 의견 있는 분들 환영입니다!

2020-03-05 07:56 UTC, yyijoo commented on manuscript/outline.md
> +- **상태 관리:** 이번 학습에서는 리액트만을 이용해 로컬 컴퍼넌트 상태를 관리했습니다. 대부분의 애플리케이션에 활용할 수 있는 좋은 시작점이지만 리액트에 적용 가능한 외부 상태 관리 솔루션들도 있습니다. 저의 책 ["리덕스 도움닫기"](https://www.roadtoredux.com/)에서 가장 대중적으로 사용되는 솔루션을 다룹니다.
반영했습니다.

2020-03-05 07:57 UTC, yyijoo commented on manuscript/outline.md
> +- **웹팩(Webpack)과 바벨(Babel) 사용** 이 책에서는 create-react-app을 사용해 애플리케이션을 설치했습니다. 어느 정도 리액트에 익숙해지면 create-react-app을 사용하지 않고 프로젝트를 다루고 싶을 것입니다. 처음에는 [웹팩](https://www.robinwieruch.de/minimal-react-webpack-
반영했습니다.

2020-03-05 08:07 UTC, yyijoo commented on manuscript/outline.md
> +- **타입 검사:** 이 책에서 리액트의 TypeScript를 사용했습니다. 이는 버그를 방지하고 개발자의 작업을 개선합니다. TypeScript를 깊이 들여다보고 적용하시면 자바스크립트 애플리케이션을 더욱 탄탄하게 만들 수 있습니다. 어쩌면 자바스크립트 대신 계속 TypeScript를 쓰게될 수도 있습니다.
이는 버그를 방지하고 개발자의 작업을 한층 수월하게 만듭니다.
우선 위와 같이 적용해보았어요!

2020-03-06 16:03 UTC, sujinleeme approved these changes
깔끔한 번역 감사합니다 :)

2020-03-06 16:03 UTC, merged