V2 파이어베이스
the-road-to-learn-react/the-road-to-learn-react-korean pull request #61
Opened 2020-03-03 12:06 UTC by yein9

제가 실수로 지난번에 올렸던 브랜치를 삭제해 버렸습니다ㅠㅠ 피드백 주셨던 것들은 모두 수정했습니다. 오탈자나 어색한 부분이 있으면 말씀해주세요:)

2020-03-03 16:49 UTC, sujinleeme commented
안녕하세요. 번역해주셔서 감사합니다. 맞춤법 검사기로 띄워쓰기 확인 부탁드립니다. 번역투가 종종 보이는데 수정 부탁드립니다.

2020-03-04 10:06 UTC, yein9 commented
리뷰 감사합니다. 띄어쓰기, 맞춤법 모두 수정했습니다. 번역기는 절대 쓰지 않았습니다!! 영어를 한글로 그대로 해석하다 보니 어색한 부분이 있었던것 같습니다ㅠㅠ 수정할 부분 알려주시면 감사하겠습니다=)

2020-03-06 16:00 UTC, sujinleeme requested changes
안녕하세요, 수고 많으셨습니다.
리뷰 검토 부탁드립니다.

2020-03-06 16:00 UTC, sujinleeme commented on manuscript/react-deploy/firebase.md
> +만약 두 번째 링크에서 빈 페이지가 보인다면, *firebase.json*의 `public` key/value pair가 `build` 폴더 혹은 이름이 변경된 폴더에 올바르게 설정되었는지 확인합니다. 다음은 리액트 애플리케이션을  `npm run build`로 빌드 스크립트를 실행했는지 체크합니다. 마지막으로, [공식적인 파이어베이스를 통한  creat
official troubleshoot area for deploying create-react-app applications to Firebase 삭제해주세요. 파이어베이스 공식 문서 내 create-react-app 배포 시 문제 해결 부분을 확인해 봅니다로 수정해주세요.

2020-03-06 16:00 UTC, sujinleeme commented on manuscript/react-deploy/firebase.md
> +- 선택: 만약 클라우드 관리 서버를 원한다면, [DigitalOcean](https://www.digitalocean.com/?refcode=fb27c90322f3&utm_campaign=Referral_Invite&utm_medium=Referral_Program&utm_source=CopyPaste)을 통해 확인 가능합니다. 클라우드 관리 서버를 사
-  선택 사항: 파이어베이스 대신 클라우드 서버를 선택하고자 한다면 [디지털 오션](https://www.digitalocean.com/?refcode=fb27c90322f3&utm_campaign=Referral_Invite&utm_medium=Referral_Program&utm_source=CopyPaste)을 추천합니다. 저의 경우 클라우드 서비스를 사용해 웹 사이트 웹 애플리케이션, 벡앤드 API를 호스팅하고 있습니다.

수정해주세요.

2020-03-06 16:00 UTC, sujinleeme commented on manuscript/react-deploy/firebase.md
> +성공적으로 배포를 하고 나면, 작성한 프로젝트와 결과가 같은지 확인을 해야 합니다.
수정 요청입니다.

* 이 과정을 통해 파이어베이스 호스팅을 위한 설정 파일을 프로젝트 폴더에 생성했습니다. -> 지금까지 프로젝트 폴더에 파이어베이스 호스팅을 관리하는 설정 파일을 생성했습니다.
* 확인을 해야 합니다. -> 확인해야 합니다.
* 파이어베이스 도큐멘트 -> 파이어베이스 공식문서
* 최종적으로 -> 마지막으로

2020-03-06 16:00 UTC, sujinleeme commented on manuscript/react-deploy/firebase.md
> +리액트 애플리케이션을 완성한 후 남은 마지막 과정은 배포입니다. 애플리케이션 배포를 통해 아이디어를 세상에 펼치는 것은 애플리케이션 제작 과정 중 가장 핵심입니다. 파이어베이스(Firebase) 호스팅으로 애플리케이션을 배포합니다.
* 수정 요청 

배포 단계는 여러분의 아이디어를 세상에 보여주는 가장 중요한 단계입니다. 이번 장에서는 파이어베이스에  리액트 앱을 배포해보겠습니다.

2020-03-06 16:00 UTC, sujinleeme commented on manuscript/react-deploy/firebase.md
> +파이어베이스 CLI를 전역으로 설치하면 프로젝트의 의존성을 신경 쓰지 않고 애플리케이션을 배포할 수 있습니다. 전역으로 설치한 노드 패키지는, 새로운 버전의 커맨드로 가능한 자주 업데이트 해주세요.
* 수정 요청

파이어베이스 CLI를 전역으로 설치해 프로젝트 의존성을 신경 쓰지 않고 애플리케이션을 배포할 수 있습니다. 전역 노드 패키지는 새로운 버전의 커맨드로 가능한 자주 업데이트 해야 합니다.

2020-03-06 16:00 UTC, sujinleeme commented on manuscript/react-deploy/firebase.md
> +만약 아직 파이어베이스 프로젝트가 없다면, [파이어베이스 계정](https://console.firebase.google.com/?pli=1)을 만들고 새로운 프로젝트를 생성합니다. 그러면 파이어베이스 CLI와 파이베이스 계정(구글 계정)과 연결할 수 있습니다.
수정 요청

* 이후 파이어베이스 CLI와 파이베이스 계정(구글 계정)과 연결합니다.

2020-03-06 16:00 UTC, sujinleeme commented on manuscript/react-deploy/firebase.md
> +이제, 프로젝트의 폴더로 이동해 아래 커맨드를 실행합니다. 이 커맨드는 파이어베이스 호스팅 특징과 관련된 파이어베이스 프로젝트를 초기화합니다.
수정 요청

* 이제,  , 를 삭제해주세요.

2020-03-06 16:00 UTC, sujinleeme commented on manuscript/react-deploy/firebase.md
> +커맨드 라인에 브라우저로 열 수 있는 URL이 표시되거나 파이어베이스 CLI가 해당 URL을 엽니다. 다음으로 구글 계정을 선택해 파이어베이스 해당하는 프로젝트를 고르고 구글의 권한 요청을 승인합니다. 다시 커맨드 라인으로 돌아와 로그인이 성공적으로 이루어졌는지 확인합니다.
수정 요청

* 커맨드 라인 보이는  브라우저 URL을 엽니다. 이후 구글 계정을 선택해 파이어베이스 해당하는 프로젝트를 고르고 권한 요청을 승인합니다. 다시 커맨드 라인으로 돌아와 로그인이 성공적으로 이루어졌는지 확인합니다.

2020-03-06 16:00 UTC, sujinleeme commented on manuscript/react-deploy/firebase.md
> +로그인을 하면 구글이 계정과 관련된 모든 파이어베이스 프로젝트를 인식합니다. 인식된 프로젝트는 파이어베이스 플랫폼에서 선택 가능합니다.
수정 요청

* 로그인을 하면 구글이 계정과 관련된 모든 파이어베이스 프로젝트를 불러옵니다.  파이어베이스 플랫폼에서 사용할 프로젝트를 선택합니다.

2020-03-06 16:00 UTC, sujinleeme commented on manuscript/react-deploy/firebase.md
> +create-react-app 애플리케이션은 `npm run build`를 처음 실행하고 나면 *build/* 폴더를 생성합니다. *build/* 폴더에는 *public/* 폴더와 *src/* 폴더에서 합쳐진 모든 자료가 있습니다. 이 애플리케이션은 한 페이지로 이루어진 애플리케이션이기 때문에 사용자를 *index.html* 파일로 리디렉트해 리액트 라우
* 수정 요청

create-react-app 애플리케이션은 `npm run build`를 처음 실행하고 나면 *build/* 폴더를 생성됩니다. *build/* 폴더에는 *public/* 폴더와 *src/* 폴더에서 합쳐진 모든 소스가 들어있습니다. 이 애플리케이션은 한 페이지로 이루어진 단일 애플리케이션이기 때문에 사용자를 *index.html* 파일로 리디렉트해 리액트 라우터가 클라이언트-사이드를 처리합니다.

2020-03-08 02:35 UTC, yein9 commented on manuscript/react-deploy/firebase.md
> +create-react-app 애플리케이션은 `npm run build`를 처음 실행하고 나면 *build/* 폴더를 생성합니다. *build/* 폴더에는 *public/* 폴더와 *src/* 폴더에서 합쳐진 모든 자료가 있습니다. 이 애플리케이션은 한 페이지로 이루어진 애플리케이션이기 때문에 사용자를 *index.html* 파일로 리디렉트해 리액트 라우
모두 수정했습니다! 리뷰 감사합니다:)

2020-03-08 16:59 UTC, sujinleeme approved these changes
멋진 번역 감사합니다. 😇

2020-03-08 17:00 UTC, merged