[v2] 리액트 레거시
the-road-to-learn-react/the-road-to-learn-react-korean pull request #62
Opened 2020-03-08 08:22 UTC by ejolie

수진님 기존 번역을 참고하여 번역했고 최대한 의역했습니다.
번역하면서 아래 두 문장이 가장 헷갈렸는데 혹시 좋은 의견 있으시면 알려주세요. 😢 
감사합니다.

- line 11
  - React components have undergone many changes, from **createClass components** over **class components**, to **function components**. Going through a React application today, it's likely that we'll see class components next to the modern function components.
  - 리액트 컴포넌트는 **createClass** 메서드로 만들어진 **클래스 컴포넌트**에서부터 **함수형 컴포넌트**까지 많은 변화를 겪어왔습니다. 오늘날의 리액트 애플리케이션에서는 클래스 컴포넌트보다 모던 함수형 컴포넌트를 먼저 보게 될 가능성이 큽니다.

- line 180
  - Where createRef is used in React's class components, React's useRef Hook is used in React function components. As React shifts towards function components, today its common practice to use the useRef hook exclusively to manage refs and apply imperative programming principles.
  - 클래스 컴포넌트에서 createRef가 사용되는 곳이 바로 함수형 컴포넌트에서 useRef 훅이 사용되는 곳입니다. 리액트가 함수형 컴포넌트로 변화하고 있기에 ref를 관리하고 명령형 프로그래밍 원리를 적용하기 위해서만 useRef 훅을 사용하는 것이 일반적입니다.

2020-03-08 16:58 UTC, sujinleeme requested changes
정말 훌륭한 번역입니다! 
몇 군데 state를 상태로 번역하면 어떨까요?

2020-03-08 16:58 UTC, sujinleeme commented on manuscript/react-legacy.md
> +리액트 훅이 등장하기 전에 클래스 컴포넌트는 상태를 가질 수 있다는 이유로 함수형 컴포넌트보다 더 우월하게 여겨졌습니다. 클래스 생성자로 클래스 컴포넌트의 초기 상태를 할당할 수 있습니다. 또한 컴포넌트의 인스턴스(`this`)는 최신 state(`this.state`)와 컴포넌트의 state 업데이트 메서드(`this.setState`)에 접근할 수 있
최신 state(`this.state`)와 컴포넌트의 state 업데이트 메서드(`this.setState`)에 접근할 수 있습니다.

 state 를 상태로 번역하면 어떨까요?

2020-03-08 16:58 UTC, sujinleeme commented on manuscript/react-legacy.md
> +리액트 클래스 컴포넌트에는 컴포넌트의 state를 관리하기 위한 두 개의 오래된(deprecated) API(`this.state` 와 `this.setState`)가 있습니다. 함수형 컴포넌트에서 useState 와 useReducer 훅이 이 일을 담당합니다. 클래스 컴포넌트는 일반적인 state API를 무조건 사용해야 하지만 함수형 컴포넌트에서 관
state 를 상태로 번역하면 어떨까요?

2020-03-09 13:37 UTC, ejolie commented on manuscript/react-legacy.md
> +리액트 클래스 컴포넌트에는 컴포넌트의 state를 관리하기 위한 두 개의 오래된(deprecated) API(`this.state` 와 `this.setState`)가 있습니다. 함수형 컴포넌트에서 useState 와 useReducer 훅이 이 일을 담당합니다. 클래스 컴포넌트는 일반적인 state API를 무조건 사용해야 하지만 함수형 컴포넌트에서 관
반영했습니다 😄

2020-03-09 13:37 UTC, ejolie commented on manuscript/react-legacy.md
> +리액트 훅이 등장하기 전에 클래스 컴포넌트는 상태를 가질 수 있다는 이유로 함수형 컴포넌트보다 더 우월하게 여겨졌습니다. 클래스 생성자로 클래스 컴포넌트의 초기 상태를 할당할 수 있습니다. 또한 컴포넌트의 인스턴스(`this`)는 최신 state(`this.state`)와 컴포넌트의 state 업데이트 메서드(`this.setState`)에 접근할 수 있
반영했습니다 😄

2020-03-09 16:39 UTC, merged