[v2] css
the-road-to-learn-react/the-road-to-learn-react-korean pull request #63
Opened 2020-03-09 08:36 UTC by haesookim

* styling은 대부분 '스타일링'으로 번역했습니다.
* 영어 용어를 그대로 사용한 부분은 이전 번역분을 참고했습니다.

2020-03-15 12:08 UTC, aeriChoi requested changes
리뷰 했습니다:)

2020-03-15 12:08 UTC, aeriChoi commented on manuscript/react-styling/css.md
> +네이밍 컨벤션 ([CSS 가이드라인](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Code_guidelines/CSS))은 리액트에서 사용되는 스타일링 방식과는 별개로 고려해야 합니다. 위에서 작성한 CSS 코드는 BEM 규칙을 따르기 때문에 클래스의 변형 형태는 언더스코어(`_`
BEM옆에 가로로 (Block Element Modifier)를 추가해주세요.

2020-03-15 12:08 UTC, aeriChoi commented on manuscript/react-styling/css.md
> +*src/App.css* 파일에 나머지 클래스들을 추가합니다.
In your src/App.css file, add the remaining classes: 영문은 삭제해주세요.

2020-03-15 12:08 UTC, aeriChoi commented on manuscript/react-styling/css.md
> +지금까지 본 것은 우리가 대부분 이미 알고 있는 기본적인 CSS이고, 조금 더 동적인 활용을 위해서는 inline style을 사용합니다. 다만 Sass(Syntactically Awesome Style Sheets: 신택스가 멋진 스타일시트)와 같은 CSS 확장 기능을 활용하지 않는다면, 네이티브 CSS에서는 상속과 같은 기능을 제공하지 않으므로 inl
inline style은 인라인 스타일로 변경해주세요.

2020-03-21 10:19 UTC, sujinleeme requested changes

2020-03-21 10:19 UTC, sujinleeme commented on manuscript/react-styling/css.md
> +# 리액트와 스타일링
제목을 리액트 스타일링이라고 하면 어떨까요?

2020-03-21 10:19 UTC, sujinleeme commented on manuscript/react-styling/css.md
> +* [마지막 섹션의 소스 코드](https://codesandbox.io/s/github/the-road-to-learn-react/hacker-stories/tree/hs/CSS-in-React)를 확인하세요.
섹션을 장으로 고쳐주세요.

2020-03-21 10:19 UTC, sujinleeme commented on manuscript/react-styling/css.md
> +지금까지 본 것은 우리가 대부분 이미 알고 있는 기본적인 CSS이고, 조금 더 동적인 활용을 위해서는 inline style을 사용합니다. 다만 Sass(Syntactically Awesome Style Sheets: 신택스가 멋진 스타일시트)와 같은 CSS 확장 기능을 활용하지 않는다면, 네이티브 CSS에서는 상속과 같은 기능을 제공하지 않으므로 inl
신택스가 멋진 스타일시트 는 번역 안해도 될 것 같은데 어떻게 생각하셔요?

2020-03-21 12:01 UTC, sujinleeme commented
https://github.com/the-road-to-learn-react/the-road-to-react-korean 에 다시 풀리퀘스트 보내주세요.

2020-03-21 12:01 UTC, closed without merging