v2/project-structure: first overall translation
the-road-to-learn-react/the-road-to-learn-react-korean pull request #64
Opened 2020-03-13 03:51 UTC by yein9

예정보다 번역이 늦어졌습니다ㅠㅠ

- component -> 컴포넌트로 사용하였습니다.

- import/report -> 수진님이 조언해주신 대로 가져오기/내보내기로 했더니 헷갈리는 것 같아 임포트/엑스포트로 사용했습니다.

- 원문에서 own file이라는 것을 전용 파일로 번역 했습니다.

-technical-oriented 를 기술-지향이 아니라 기능 지향으로 번역했습니다.

외에도 수정할 사항이다 피드백 주시면 감사하겠습니다! 다들 건강 조심하세요:)

2020-03-13 03:53 UTC, yein9 commented on manuscript/react-maintenance/project-structure.md
> +더 깊은 레벨의 폴더 구조로 확장해나가면, 아래의 예시처럼 컴포넌트 각자의 역할에 맞는 자체 폴더가 있습니다.
이부분 해석이 잘 안된것 같습니다ㅠㅠ 어떻게 바꾸면 좋을까요??

2020-03-14 18:15 UTC, sujinleeme requested changes

2020-03-14 18:15 UTC, sujinleeme commented on manuscript/react-maintenance/project-structure.md
> +* [지난 섹션의 소스코드](https://codesandbox.io/s/github/the-road-to-learn-react/hacker-stories/tree/hs/React-Folder-Structure) 확인하기.
섹션을 장으로 고쳐주시고 마침표는 삭제해주세요.

2020-03-14 18:15 UTC, sujinleeme commented on manuscript/react-maintenance/project-structure.md
> +### 읽어보기:
: 를 삭제해주세요.

2020-03-14 18:15 UTC, sujinleeme commented on manuscript/react-maintenance/project-structure.md
> +리액트 프로젝트를 재구성하기 전에, [자바스크립트의 임포트(import)와 엑스포트(export)](https://www.robinwieruch.de/javascript-import-export)에 대해 알아봅시다. 파일 임포트와 엑스포트는 리액트를 공부하기 전 꼭 알아야 할 자바스크립트의 중요 개념입니다. 리액트 애플리케이션은 프로젝트를 진행해 가면서
import(가져오기) 구문 export(내보내기)  구문 으로 바꾸는게 좋을 것 같아요.

다른 저서나 문서에도 그대로 사용하고 있어요.

2020-03-14 18:15 UTC, sujinleeme commented on manuscript/react-maintenance/project-structure.md
> +이제 프로세스에 대해 알아보기 위해 프로젝트의 폴더와 파일 리팩토링을 해보겠습니다. 이후엔 리액트 프로젝트를 재구성하는 옵션도 살펴봅니다. 이 과정은 간단히 하기 위해 *src/App.js*를 사용해 실습을 진행하도록 하겠습니다.
*src/App.js* 파일에서로 수정해주세요.

2020-03-14 18:15 UTC, sujinleeme commented on manuscript/react-maintenance/project-structure.md
> +커맨드 라인에서 프로젝트의*src/*폴더로 이동해 아래의 커맨드처럼 컴포넌트 전용 파일을 생성합니다.
띄워쓰기 해주세요.

> 프로젝트 내  *src/ *폴더

2020-03-14 18:15 UTC, sujinleeme commented on manuscript/react-maintenance/project-structure.md
> +*src/List.js* 파일과 공유하는 Item 컴포넌트를 제외한  *src/App.js*에 있던 모든 컴포넌트를 각자 전용 파일로 분리합니다. 이후 모든 파일에 리액트를 임포트 하고 다른 파일에서 사용되는 컴포넌트는 엑스포트를 해야 합니다. 예를 들어, 아래의 *src/List.js* 파일이 있습니다.
수정해주세요. 

모든 컴포넌트를 각자 전용 파일로 분리합니다.

-> 모든 컴포넌트를 각 파일로 분리합니다.

2020-03-14 18:15 UTC, sujinleeme commented on manuscript/react-maintenance/project-structure.md
> +만약 CSS 파일이 필요 없는 CSS-in-JS를 사용한다면,  styled component 전용 *style.js* 파일을 가질 수 있습니다.
가질 수 있습니다를 만들 수 있습니다 라고 수정해주세요.

2020-03-14 18:15 UTC, sujinleeme commented on manuscript/react-maintenance/project-structure.md
> +더 깊은 레벨의 폴더 구조로 확장해나가면, 아래의 예시처럼 컴포넌트 각자의 역할에 맞는 자체 폴더가 있습니다.
폴더 구조가 점점 복잡해지면, 컴포넌트 별로 폴더를 분리하고 역할에 따라 파일을 만들 수 있습니다. 라고 하면 어떨까요.

2020-03-15 08:09 UTC, yein9 commented
수진님이 주신 피드백 모두 수정했습니다:) 혹시 import의 경우는 'import 해야한다.' /'import해야 한다'  둘 중 어떻게 해석하는 것이 좋을까요??

2020-03-15 13:34 UTC, sujinleeme requested changes

2020-03-15 13:34 UTC, sujinleeme commented on manuscript/react-maintenance/project-structure.md
> +*src/List.js* 파일과 공유하는 Item 컴포넌트를 제외한  *src/App.js*에 있던 모든 컴포넌트를 각 파일로 분리합니다. 이후 모든 파일에 리액트를 import 하고 다른 파일에서 사용되는 컴포넌트는 export해야 합니다. 예를 들어, 아래의 *src/List.js* 파일이 있습니다.
이후 모든 파일에 import 구문으로 리액트를 불러오고, 만든 컴포넌트는 export 구문으로 내보내야합니다.

어떨까요?

2020-03-15 13:34 UTC, sujinleeme commented on manuscript/react-maintenance/project-structure.md
> +* [자바스크립트 import/export 구문](https://www.robinwieruch.de/javascript-import-export)에 대해 더 읽어보기
import 및 export 구문 으로 수정해주세요.

2020-03-15 13:34 UTC, sujinleeme commented on manuscript/react-maintenance/project-structure.md
> +App 컴포넌트는 render 함수에서 사용되는 컴포넌트들을 모두 import해야 합니다. InputWithLabel 컴포넌트는 SearchForm 컴포넌트에서만 사용되기 때문에 App 컴포넌트에서는 import하지 않아도 됩니다.
첫 문장에 
컴포넌트들을 모두 import해야 합니다. 부분을 
import 구문으로 불러와야 합니다. 라고 수정하면 어떨까요?

2020-03-15 13:34 UTC, sujinleeme commented on manuscript/react-maintenance/project-structure.md
> +List 컴포넌트만 Item 컴포넌트를 사용하기 때문에, Item 컴포넌트와 List 컴포넌트는 같은 파일에 보관해도 됩니다. 만약 다른 컴포넌트도 Item 컴포넌트를 사용하면 Item 컴포넌트 전용 파일을 따로 만드는 것이 좋습니다. *src/SearchForm.js* 파일의 SearchForm 컴포넌트는 반드시 InputWithLabel 컴포넌트를 i
여기도 위에 처럼 바꿀 수 있을 것 같아요.

2020-03-21 12:01 UTC, sujinleeme commented
https://github.com/the-road-to-learn-react/the-road-to-react-korean 에 다시 풀리퀘스트 보내주세요.

2020-03-21 12:01 UTC, closed without merging